### ISSUE TITLE
独自ドメインの設定について

### ISSUE THREAD

**Issue by hiro97617** [hiro97617/phonics_trainer#136]
独自ドメイン取得に関してエラーが起きています。
ドメイン周りの状況は下記の通りです。
1. お名前.comでのドメイン取得には成功しています。picture1とpicture2をご覧ください。
![picture1](https://github.com/hiro97617/phonics_trainer/assets/113866577/e4805354-1cfe-4730-80d8-5a441b5ae2b7)
![picture2](https://github.com/hiro97617/phonics_trainer/assets/113866577/4c0f008a-e2f5-4f4e-a232-272d1098ef31)

2. お名前.comでDNS周辺の設定を行いました。picture3をご覧ください。
![picture3](https://github.com/hiro97617/phonics_trainer/assets/113866577/6e81c7dd-3e88-4caa-8b58-64a2f05bcf7b)

3. heroku周りも設定を行いました。
 - heroku domainsとターミナルで打つとpicture4のようになります。
![picture4](https://github.com/hiro97617/phonics_trainer/assets/113866577/0061eefb-1e94-46aa-a490-3df24b5b1367)

 - ダッシュボードではpicture5のようになります。
 ![picture5](https://github.com/hiro97617/phonics_trainer/assets/113866577/51249be2-dc66-4e7b-87de-86eeafabb04f)

4. エラーの原因を見ると、"Unable to resolve DNS for domain"と書いてあったので、Google's DNSを確認してpicture6のような結果が出ました。
![picture6](https://github.com/hiro97617/phonics_trainer/assets/113866577/4198e362-217a-428e-9140-c5e6c1e16b39)

5. また、独自ドメインとIPアドレスの取得ができているかをwhois検索を用いて行い、IPアドレスも取得されていることがわかりました。そのIPアドレスをGoogle's DNSに入れて、picture7のような結果になりました。　
![picture7](https://github.com/hiro97617/phonics_trainer/assets/113866577/4ba36ed4-c255-457c-b60a-f70b5b91a224)

また、phonicstrainerのアドレスである、[http://phonicstrainer.com](http://phonicstrainer.com)や[http://www.phonicstrainer.com](http://www.phonicstrainer.com)と入力しても、アプリが見つかりませんという結果が出ました。
これらの結果から、独自ドメインの取得まではいっているけど、僕のアプリと独自ドメインの連携や繋がりが上手くいっていないと思いました。
解決策を教授してくださると幸いです。
よろしくお願いします

**Comment by kerochelo** [comment]
@hiro97617 
いつごろ設定したでしょうか、もしかしたら反映するまで24-72時間かかるようなので、少し待つかもしれないです。（早い人は1時間くらいで来る）
参考にしたドキュメントあれば共有いただきたいです:bow:

**Comment by hiro97617** [comment]
返信してくださり、ありがとうございます。
設定自体はかなり前にやって(2~3週間前に)、待てど反映されませんでした。
その後に土曜日にもう一度着手しました。

お伝えしておらず、すみません！
参考にしたドキュメントは下記の通りです。
最初は無料でやろうとしていました。その際に参考にしたドキュメントはこれです。
[https://osamudaira.com/461/](https://osamudaira.com/461/)
[https://qiita.com/kenjikatooo/items/07c3d911210a4ca96781](https://qiita.com/kenjikatooo/items/07c3d911210a4ca96781)
途中で有料プランに切り替えて、参考にしたドキュメントはこちらです。
[https://qiita.com/tky529/items/0a578ae06b0338b3b240](https://qiita.com/tky529/items/0a578ae06b0338b3b240)
[https://devcenter.heroku.com/articles/automated-certificate-management#view-your-certificate-status](https://devcenter.heroku.com/articles/automated-certificate-management#view-your-certificate-status)
[https://devcenter.heroku.com/ja/articles/custom-domains](https://devcenter.heroku.com/ja/articles/custom-domains)

よろしくお願い致します。

**Comment by kerochelo** [comment]
@hiro97617 
ありがとうございます！sshの証明書がエラーになっているようですね
HerokuからACM設定が失敗してるメールきてたりしますかね？
またお名前.comのcname設定のvalueってDNSターゲット用の「www.hoge.com.**herokudns.com**」
みたいになっていますかね？

**Comment by hiro97617** [comment]
@kerochelo 
返事してくださり、ありがとうございます！！
そうですね、メールは下記のようにきています。

![heroku_email](https://github.com/hiro97617/phonics_trainer/assets/113866577/681e37bd-0da2-4e36-840b-4a0f2635bfed)

また、お名前.comのcname設定のvalueってDNSターゲット用の部分はherokudns.comという形にはなっています。
しかし、気になることがありまして、そこのDNS Targetはcylindri・・・tlj.herokudns.comとなっていて、www.phonicstrainer.com.herokudns.comという感じにはなっていません。
cylindri・・・tlj.herokudns.comはダッシュボードのDomain Nameの隣にあるDNS Targetを参照しています。(オレンジ色の枠の部分です)
![heroku_dashboard](https://github.com/hiro97617/phonics_trainer/assets/113866577/5b632f1e-820b-4020-98e3-ade30a32f8e6)

よろしくお願い致します。

**Comment by kerochelo** [comment]
@hiro97617 
リファレンスのtroubleshooting見る限りだと「The DNS targets will be in the format <your-domain>.herokudns.com」となっているので、ドメインの部分に問題があるかもしれないです、
この内容を確認して、再度設定を試してしてもらっていいですか。
https://devcenter.heroku.com/articles/automated-certificate-management#troubleshooting

**Comment by hiro97617** [comment]
承知しました！！
トラブルシューティングとドメイン関連のドキュメントを確認しました。
そこで気になる記述がありました。

<img width="405" alt="edit_domain_screen" src="https://github.com/hiro97617/phonics_trainer/assets/113866577/21cae9a6-7ef2-4c8c-80da-6f5b2571d15b">

この"Rules on adding domains"を見ると、
<img width="642" alt="rules_on_adding_domains" src="https://github.com/hiro97617/phonics_trainer/assets/113866577/5f909f49-bf77-4ffe-8b81-89aa95f88b3a">
と書いてあります。
オレンジの枠には、"You can add a subdomain or apex domain if you own the app that is assigned the corresponding wildcard domain. For example, to add www.example.com or example.com, you must own the app with *.example.com (if such a custom domain exists)."(対応するワイルドカードドメインが割り当てられているアプリを所有している場合、サブドメインまたはエイペックスドメインを追加できます。例えば、www.example.com または example.com を追加するには、*.example.com（そのようなカスタムドメインが存在する場合）を持つアプリを所有する必要があります。)とあります。

ですので、ワイルドカードドメインも同時に設定する方がいいですか？
お手数お掛けしますが、よろしくお願いします。

**Comment by kerochelo** [comment]
@hiro97617 
サブドメインなどで利用しない場合はワイルドカードを設定する必要がないので、今回は設定なしで大丈夫かなと！

**Comment by hiro97617** [comment]
わかりました！！
ありがとうございます！！

**Comment by hiro97617** [comment]
[https://qiita.com/ozin/items/62bc7ef1dd3c827177fb](https://qiita.com/ozin/items/62bc7ef1dd3c827177fb)
[https://qiita.com/tksh8/items/ab3748bcb01316461abe](https://qiita.com/tksh8/items/ab3748bcb01316461abe)

これらをもとにして、独自ドメインを再度設定します！

**Comment by hiro97617** [comment]
今、お名前どっとこむをみたら、phonicstrainer.comが
phoincs.comとタイプミスしていました....(しかし、herokuの方ではずっとwww.phonicstrainer.comで行っていました。)
それで出来なかったのかなと思い、herokuの方もwww.phoincstrainer.comで設定しました。

**Comment by hiro97617** [comment]
独自ドメイン取れました！！！！！
<img width="1253" alt="succeed_domain" src="https://github.com/hiro97617/phonics_trainer/assets/113866577/c40df2fc-9314-4660-a3aa-46b44b3d2772">
